app:
  host: '0.0.0.0'
  port: 8003

data_service:
  base_url: http://localhost:8002
  timeout: 5
  retries:
    max_attempts: 2
    delay: 1
  
redis:
  host: localhost
  port: 6379
  ttl: 86400 #24 hours
  timeout: 5