version: '1.0'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8085:8080"

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shift_user
      POSTGRES_PASSWORD: shift_password
      POSTGRES_DB: shift_db_pg

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  data-service:
    build: 
      context: ./data-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - kafka
    environment:
      DATABASE_URL: postgresql+asyncpg://shift_user:shift_password@postgres:5432/shift_db_pg
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  flow-selection-service:
    build: 
      context: ./flow-selection-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - data-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DATA_SERVICE_URL: http://data-service:8002

  scoring-service:
    build: 
      context: ./scoring-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - antifraud-service
      - data-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATA_SERVICE_URL: http://data-service:8002
  
  antifraud-service:
    build:
      context: ./antifraud-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - data-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DATA_SERVICE_URL: http://data-service:8002
