apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-flow-{{ .Values.labels.student }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- toYaml .Values.labels | nindent 4}}
data: 
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.jaegerUrl }}"
  SERVICE_NAME: "{{ .Values.labels.app }}"
  STUDENT_NAME: "{{ .Values.labels.student }}"
  REDIS_HOST: "{{ .Values.config.redisHost }}"
  REDIS_PORT: "{{ .Values.config.redisPort }}"
  KEY_PREFIX: "{{ .Values.config.redisPrefix }}"
  config.yaml: |
    app:
      host: {{ .Values.config.host }}
      port: {{ .Values.config.port }}
    redis:
      {{- toYaml .Values.config.redis | nindent 6 }}
    data_service:
      {{- toYaml .Values.config.data_service | nindent 6 }}