apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-flow-aabalymov
  namespace: test
  labels:
    student: aabalymov
    app: flow-selection-service
data:
  REDIS_PASSWORD: c2hpZnRfMjAyNV9weXRob24=