apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-data-service-aabalymov
  namespace: test
  labels:
    student: aabalymov
    app: data-service
stringData:
  DATABASE_URL: "postgresql+asyncpg://aabalymov:9HntOnCSiQBDT3ZO@postgres-service.infra.svc.cluster.local:5432/aabalymov"