apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-scoring-aabalymov
  namespace: test
  labels:
    student: aabalymov
    app: scoring-service
data:
  config.yaml: |
    app:
      host: '0.0.0.0'
      port: 8001

    data_service:
      base_url: "http://data-service-aabalymov.test.svc.cluster.local:8002"
      timeout: 5
      retries:
        max_attempts: 2
        delay: 1
    
    kafka:
      bootstrap_servers: 'infra-kafka.infra.svc.cluster.local:9092'
      topic: 'aabalymov_scoring_events'
