apiVersion: v1
kind: Service
metadata:
  name: scoring-service-aabalymov
  namespace: test
  labels:
    student: aabalymov
    app: scoring-service
spec:
  selector:
    app: scoring-service
  ports:
  - port: 8001
    targetPort: 8001