apiVersion: v1
kind: Service
metadata:
  name: flow-selection-service-aabalymov
  namespace: test
  labels:
    student: aabalymov
    app: flow-selection-service
spec:
  selector:
    app: flow-selection-service
  ports:
  - port: 8000
    targetPort: 8000