apiVersion: v1
kind: Service
metadata:
  name: data-service-{{ .Values.labels.student }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-service.labels" . | nindent 4 }}
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
  selector:
    app: data-service
